name: CI
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js v16.14.0
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      - name: Build
        run: |
          yarn set version berry
          yarn install --immutable
          yarn build
      - name: Unit Testing & Coverage
        run: yarn coverage
      - name: e2e Testing
        run: |
          yarn dlx playwright install-deps
          yarn test:e2e
