name: Release to GitHub Pages

on: [push, pull_request]

jobs:
  CICD:
    name: Release to GitHub Pages
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js v16.14.0
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      - name: Install project deps
        run: |
          yarn set version berry
          yarn install --immutable --immutable-cache

      - name: Cache NextJS
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('yarn.lock') }}-

      - name: Build NextJS
        run: |
          yarn next telemetry disable > /dev/null
          NEXT_BASE_PATH=$(basename ${{ github.repository }}) yarn build

      - name: Unit testing & check code coverage
        run: yarn coverage

      - name: Cache playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: cache-playwright-${{ runner.os }}
      - name: Install playwright deps
        run: |
          yarn dlx playwright install --with-deps --dry-run
          yarn dlx playwright install --with-deps
        if: always()
      - name: e2e Testing
        run: yarn test:e2e
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: test-results

      - name: Release to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./out
